// lib/DummyData.ts

export interface ExpenseBudget {
  _id: string;
  name: string;
  spent: number;
  limit: number;
  isAutoGenerated?: boolean;
}

export interface Expense {
  _id: string;
  date: string;
  category: string;
  amount: number;
}

export interface ChartDataPoint {
  name: string;
  expenses: number;
  savings: number;
}

// Dummy budgets data
export const budgetsData: ExpenseBudget[] = [
  { _id: "1", name: "Food", spent: 300, limit: 500 },
  { _id: "2", name: "Transport", spent: 120, limit: 200 },
  { _id: "3", name: "Entertainment", spent: 150, limit: 250 },
  { _id: "4", name: "Grocery", spent: 220, limit: 400 },
  { _id: "5", name: "Urgent", spent: 100, limit: 150 },
];

// Dummy expenses data
export const expensesData: Expense[] = [
  { _id: "e1", date: "2025-08-01", category: "Food", amount: 50 },
  { _id: "e2", date: "2025-08-02", category: "Transport", amount: 20 },
  { _id: "e3", date: "2025-08-03", category: "Entertainment", amount: 30 },
  { _id: "e4", date: "2025-08-04", category: "Grocery", amount: 40 },
  { _id: "e5", date: "2025-08-05", category: "Urgent", amount: 60 },
];

// Dummy chart data
export const chartData: ChartDataPoint[] = [
  { name: "Week 1", expenses: 300, savings: 200 },
  { name: "Week 2", expenses: 250, savings: 250 },
  { name: "Week 3", expenses: 400, savings: 100 },
  { name: "Week 4", expenses: 200, savings: 300 },
];

// User profile dummy data
export const userProfileData = {
  monthlySalary: 5000,
  savingsPercentage: 20, // 20%
};

export const monthlySavingGoalData = {
  _id: "monthly-goal-august-2025",
  name: "This Month's Saving Goal",
  target: 1000,
  saved: 450.0,
};
